import React from 'react'
import Head from 'next/head'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'
import 'bootstrap/dist/css/bootstrap.css'
const layout = ({ children }) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                {/* <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" /> */}

                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

            </Head>

            <NavBar />
            <main>
                {children}
            </main>
            <Footer />



        </div>


    )
}

export default layout
